[package]
name = "descord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
descord = "0.1.7"
dotenvy = "0.15.7"
lazy_static = "1.4.0"
reqwest = { version = "0.11.27", features = ["json"] }
tokio = "1.36.0"
